export const sample_foods = [
  {
    name: 'Chicken Biryani',
    price: 12,
    cookTime: '30-40',
    favorite: false,
    origins: ['india'],
    stars: 4.8,
    imageUrl: 'chickenbiriyani.jpg',
    tags: ['Indian', 'Biryani', 'Lunch'],
  },
  {
    name: 'Mutton biriyani',
    price: 15,
    cookTime: '30-40',
    favorite: false,
    origins: ['india'],
    stars: 4.8,
    imageUrl: 'mutton biriyani.jpg',
    tags: ['Indian', 'Biryani', 'Lunch'],
  },
  {
    name: 'Veg Biryani',
    price: 10,
    cookTime: '25-35',
    favorite: true,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'vegetable-biryani.jpg',
    tags: ['Indian', 'Biryani', 'Lunch','Vegetarian'],
  },
  {
    name: 'Roti',
    price: 1,
    cookTime: '5-10',
    favorite: false,
    origins: ['india'],
    stars: 4.0,
    imageUrl: 'Roti.jpg',
    tags: ['Indian', 'Bread', 'Dinner'],
  },
  {
    name: 'Naan',
    price: 2,
    cookTime: '10-15',
    favorite: true,
    origins: ['india'],
    stars: 4.2,
    imageUrl: 'naan.jpg',
    tags: ['Indian', 'Bread', 'Dinner'],
  },
  {
    name: 'Natu Koli Kulambu',
    price: 15,
    cookTime: '40-50',
    favorite: false,
    origins: ['india'],
    stars: 4.7,
    imageUrl: 'nattu-koli-kolambu.jpg',
    tags: ['Indian', 'Gravy', 'Dinner'],
  },
  {
    name: 'Pepper Fry',
    price: 18,
    cookTime: '25-30',
    favorite: true,
    origins: ['india'],
    stars: 4.6,
    imageUrl: 'pepperfry.png',
    tags: ['Indian', 'Fry', 'Dinner'],
  },
  {
    name: 'Mango Ice Cream',
    price: 8,
    cookTime: '5-10',
    favorite: false,
    origins: ['india'],
    stars: 4.3,
    imageUrl: 'mango icecream.jpg',
    tags: ['Indian', 'Dessert', 'Ice Cream'],
  },
  {
    name: 'Gulab Jamun',
    price: 6,
    cookTime: '15-20',
    favorite: true,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'Gulab-Jamun.jpg',
    tags: ['Indian', 'Dessert', 'Sweet'],
  },
  {
    name: 'Masala Chai',
    price: 3,
    cookTime: '10-15',
    favorite: false,
    origins: ['india'],
    stars: 4.0,
    imageUrl: 'Masala-Chai-Tea.jpg',
    tags: ['Indian', 'Beverage', 'Tea'],
  },
  {
    name: 'Paneer Tikka',
    price: 14,
    cookTime: '20-25',
    favorite: true,
    origins: ['india'],
    stars: 4.4,
    imageUrl: 'Paneer-Tikka.jpg',
    tags: ['Indian', 'Appetizer', 'Vegetarian'],
  },
  {
    name: 'Dosa',
    price: 7,
    cookTime: '15-20',
    favorite: false,
    origins: ['india'],
    stars: 4.2,
    imageUrl: 'Dosa.jpg',
    tags: ['Indian', 'Breakfast', 'South Indian'],
  },
  {
    name: 'Hyderabadi Biryani',
    price: 16,
    cookTime: '35-45',
    favorite: true,
    origins: ['india'],
    stars: 4.9,
    imageUrl: 'hydrabad biriyani.jpg',
    tags: ['Indian', 'Biryani', 'Lunch'],
  },
  // Add more food items here...
];

export const sample_tags = [
  { name: 'All', count: 20 },
  { name: 'Indian', count: 20 },
  { name: 'Biryani', count: 4 },
  { name: 'Lunch', count: 5 },
  { name: 'Dinner', count: 8 },
  { name: 'Bread', count: 2 },
  { name: 'Gravy', count: 2 },
  { name: 'Fry', count: 2 },
  { name: 'Dessert', count: 3 },
  { name: 'Ice Cream', count: 1 },
  { name: 'Sweet', count: 2 },
  { name: 'Beverage', count: 1 },
  { name: 'Tea', count: 1 },
  { name: 'Appetizer', count: 1 },
  { name: 'Vegetarian', count: 1 },
  { name: 'Breakfast', count: 1 },
  { name: 'South Indian', count: 1 },
  // Add more tags here...
];
  export const sample_users = [
    {
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: false,
    },
    {
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];